# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'singleNum.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_single_input(object):
    def setupUi(self, single_input):
        single_input.setObjectName("single_input")
        single_input.resize(323, 70)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(single_input.sizePolicy().hasHeightForWidth())
        single_input.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("shinnku.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        single_input.setWindowIcon(icon)
        single_input.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(single_input)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(single_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(single_input)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 1, 1, 1)

        self.retranslateUi(single_input)
        self.buttonBox.accepted.connect(single_input.accept) # type: ignore
        self.buttonBox.rejected.connect(single_input.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(single_input)

    def retranslateUi(self, single_input):
        _translate = QtCore.QCoreApplication.translate
        single_input.setWindowTitle(_translate("single_input", "请输入题目数量"))
